### ISSUE TITLE
Questions about NDMS

### ISSUE THREAD

**Issue by LaLaLailalai** [jutanke/ndms#1]
Hi @jutanke ,

Thanks for your excellent work! 

I'm interested in the metric NDMS, and I have a question about it. According to your utilization sample, why should we use function ` db.rolling_query(seq)` to compute the NDMS but not use [NDMS ](https://github.com/jutanke/ndms/blob/8894f80adae6bf91f835ac8859e69f97757cf655/ndms/ndms.py#L9) function in ndms.py directly?  If the NDMS results of your method in your paper are calculated by using ` db.rolling_query(seq)`?

**Comment by jutanke** [comment]
This is formulated a bit awkward in the paper: in our paper we actually report the frame-wise values ```g``` (Eq. 10) averaged over the number of samples rather than the accumulated one ```f_{sim}``` (Eq. 9).
Accumulating the scores will punish (big) mistakes that happen early in the prediction more and it scores recovering from bad motion much lower.
On the other hand, using framewise scores allows us to pinpoint when the generated motion becomes "bad" but it will also be more lenient when the motion generation recovers from bad poses. In the end, many motion anticipation methods have a design flaw that makes the first few generated poses seem "disconnected" to the input motion - these kind of design flaws can only be caught with the framewise score which is why we use that version in the paper.
